services:
  - type: web
    name: ai-text-analyser
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    region: frankfurt
    branch: main
    autoDeploy: true
